<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>essl</string>
		<string>f.essl</string>
		<string>v.essl</string>
		<string>_v.essl</string>
		<string>_f.essl</string>
		<string>_vs.essl</string>
		<string>_fs.essl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>ESSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(break|continue|discard|do|else|for|if|return|while)\b</string>
			<key>name</key>
			<string>keyword.control.essl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(void|mat2|mat3|mat4|vec2|vec3|vec4|ivec2|ivec3|ivec4|bvec2|bvec3|bvec4|sampler2D|samplerCube|struct)\b</string>
			<key>name</key>
			<string>storage.type.essl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(attribute|const|in|inout|out|uniform|varying|invariant|lowp|mediump|highp|precision)\b</string>
			<key>name</key>
			<string>storage.modifier.essl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(gl_Position|gl_PointSize|gl_FragCoord|gl_FrontFacing|gl_FragColor|gl_FragData|gl_PointCoord)\b</string>
			<key>name</key>
			<string>support.variable.essl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(gl_MaxVertexAttribs|gl_MaxVertexUniformVectors|gl_MaxVaryingVectors|gl_MaxVertexTextureImageUnits|gl_MaxCombinedTextureImageUnits|gl_MaxTextureImageUnits|gl_MaxFragmentUniformVectors|gl_MaxDrawBuffers|gl_DepthRange|__VERSION__|GL_ES)\b</string>
			<key>name</key>
			<string>support.constant.essl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(radians|degrees|sin|cos|tan|asin|acos|atan|atan|pow|exp|log|exp2|log2|sqrt|inversesqrt|abs|sign|floor|ceil|fract|mod|mod|min|max|clamp|mix|step|smoothstep|length|distance|dot|cross|normalize|faceforward|reflect|refract|matrixCompMult|lessThan|lessThanEqual|greaterThan|greaterThanEqual|equal|notEqual|any|all|not|texture2D|texture2DProj|texture2DLod|texture2DProjLod|textureCube|textureCubeLod)\b</string>
			<key>name</key>
			<string>support.function.essl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(asm|class|union|enum|typedef|template|this|packed|goto|switch|default|inline|noinline|volatile|public|static|extern|external|interface|flat|long|short|double|half|fixed|unsigned|superp|input|output|hvec2|hvec3|hvec4|dvec2|dvec3|dvec4|fvec2|fvec3|fvec4|sampler1D|sampler3D|sampler1DShadow|sampler2DShadow|sampler2DRect|sampler3DRect|sampler2DRectShadow|sizeof|cast|namespace|using)\b</string>
			<key>name</key>
			<string>invalid.illegal.essl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.essl</string>
	<key>uuid</key>
	<string>5370EFAA-07AA-4597-962E-D051A99C57A9</string>
</dict>
</plist>
